# 12-Layer Balanced CNN Config
model:
  name: 'balanced_12layer'
  num_classes: 10

training:
  num_epochs: 80
  learning_rate: 0.001
  weight_decay: 0.05  # AdamW for L2
  scheduler: 'CosineAnnealingWarmRestarts'
  t_0: 15
  t_mult: 2
  batch_size: 64
  early_stopping_patience: 15
  class_weights: [1.0, 0.8, 1.3, 1.0, 1.3, 1.0, 1.3, 0.8, 1.0, 0.8]  # Balanced for confused classes

data:
  batch_size: 64
  num_workers: 4
  random_seed: 42
  download: true

device: 'cuda' if torch.cuda.is_available() else 'cpu'
mixed_precision: true  # FP16
